### ISSUE TITLE
Crystal v0.30.1 changed HTTP::Request#initialize signature

### ISSUE THREAD

**Issue by lagr** [spinscale/crystal-aws-lambda#4]
Hello there,

first of all: thank you for laying the groundwork of bringing Crystal to Lambdas!

With Crystal still in its shaping, some things tend to break – in this case, I think the signature of `HTTP::Request.initialize` has been changed somewhere between `0.28.0` and `0.30.1` to accommodate some header safeguarding. 

While fiddling around with your shard, I noticed that I needed to patch 

https://github.com/spinscale/crystal-aws-lambda/blob/e3f89dbe7e213f1bccd7bc656cd84c3ba9f72d8e/src/lambda_builder/http_request.cr#L27

to include `, internal: nil` in order to stick to the the new method signature. In case you are still maintaining this shard, I thought this hint might save you some time when upgrading to v0.30.1.

Best regards 🙂

**Comment by spinscale** [comment]
thank you for the notice, much appreciated. just updated dependencies and fixed this one!
